services:
  dockercomposetest_api:
    image: fritzthecat9/dockercomposetest_api:${SYSTEM_TAG}
    container_name: dockercomposetest_api
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: DockerComposeTest.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "${HOME_VARIABLE}/.aspnet/https:/https/"

  dockercomposetest_api2:
    image: fritzthecat9/dockercomposetest_api2:${SYSTEM_TAG}
    container_name: dockercomposetest_api2
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: DockerComposeTest.Api2/Dockerfile
    ports:
      - 5002:5002
      - 5003:5003
    environment:
      - ASPNETCORE_URLS=https://+:5003;http://+:5002
      - ASPNETCORE_HTTP_PORTS=5002
      - ASPNETCORE_HTTPS_PORTS=5003
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "${HOME_VARIABLE}/.aspnet/https:/https/"